### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by tarunreddykaithe** [aadel/sqlalchemy-solr#1]
It throws ca't load plugin error when i try to connect to solr

**Comment by aadel** [comment]
Just restart Superset after installing the dialect.

**Comment by tarunreddykaithe** [comment]
Thanks for replying.

I restarted the whole server and Superset. I still have the issue.

**Comment by aadel** [comment]
Could you provide more details about the environment, such as Superset version and the output of running setup.py? The issue could be regenerated and resolved by restarting to reload the dialects but to proceed further more details are required in this case.---- On Tue, 31 Mar 2020 07:01:32 +0200  tarunreddykaithe<notifications@github.com> wrote ---- 
Thanks for replying. 
I restarted the whole server and Superset. I still have the issue.

**Comment by tarunreddykaithe** [comment]
Superset version=0.23
Output of running setup.py = sqlalchemy-solr is installed succesfully.

Please let me know if you need anything else.

**Comment by aadel** [comment]
The same on Superset 0.23.2 as 0.35.2. The issue could be regenerated and resolved by just restarting Superset.
