### ISSUE TITLE
Support for JWT Auth Token

### ISSUE THREAD

**Issue by rohitpawar2811** [aadel/sqlalchemy-solr#11]
Hi,

I'm reaching out regarding an issue with sqlalchemy-solr. Currently, only Basic-Auth is supported . The request is for adding Jwt Auth Token support when connecting to Solr.

Current connection:
```solr://username:XXXXXXXXXX@host:8983/solr/local-enterpriseSearch```

Desired connection:
```solr://172.20.20.244:8983/solr/local-enterpriseSearch?token=13224212....```

Thanks!

**Comment by rohitpawar2811** [comment]
Hi @aadel, I am creating a PR regarding this enhancement and some fixes. I would like your help in understanding something.

Can you explain the exact use case of the `SolrTableReflection` class and why we are iterating over tables here? 
In the case of a simple `SELECT * FROM table_name`, we wouldn't iterate over the loop. **Are we handling aliases or Cross Join support use case**

for table in tables:
    if table not in SolrTableReflection.table_metadata_cache:
        session = SolrTableReflection.connection._session

**Comment by rohitpawar2811** [comment]
@aadel 
Here is the PR for the enhancement: https://github.com/aadel/sqlalchemy-solr/pull/15/files
Please review the changes, and if you find anything incorrect, kindly let me know.
Thank you.

**Comment by aadel** [comment]
Hi @rohitpawar2811 Thank you for your contribution! `SolrTableReflection` class responsibility is to deduce and map metadata from Solr index given the resultset and the query. The class implements a simple caching mechanism for which the depicted loop above represents a cache miss.

At this time, aliases and cross join use cases are not supported. However, I have added a new issue #16 for handling aliases.

**Comment by rohitpawar2811** [comment]
Closing this enchancement issue as its completed in below 
MR: https://github.com/aadel/sqlalchemy-solr/pull/15
