### ISSUE TITLE
Contributing to the source code

### ISSUE THREAD

**Issue by ichux** [aadel/sqlalchemy-solr#21]
@aadel 

I want to know how I can contribute to the source code. Some improvements are helpful towards ensuring we have a library that's able to do more.

I have made some changes and will wait to hear back from you

**Comment by aadel** [comment]
Hello @ichux -- Thank you for your interest! Please open issues here with your feature requests, improvements, fixes, or suggestions and we can continue from there.

**Comment by ichux** [comment]
OK, noted. I will do so
