### ISSUE TITLE
Remove semicolon from query

### ISSUE THREAD

**Issue by f-gerle** [aadel/sqlalchemy-solr#31]
Solr does not accept SQL Queries terminated by a semicolon (;). To ensure compatibility with other packages that generate terminated SQL queries, a trailing semicolon should be removed before sending the query to the solr. 

As a quick fix, I added the line `query = query.replace(';', '')` to `substitute_in_query` in the `Cursor` class.

**Comment by aadel** [comment]
@f-gerle this should be handled by the driver in release [0.2.4.3](https://github.com/aadel/sqlalchemy-solr/releases/tag/v0.2.4.3). It seems that the semi-colon needs to be removed in text queries mode only and the ORM does not generate it.

Thanks for reporting!
