### ISSUE TITLE
How to handle multivalued Solr fields?

### ISSUE THREAD

**Issue by anjackson** [aadel/sqlalchemy-solr#4]
If a query return values from a multivalued column, this error occurs:

    TypeError: <class 'list'> is not convertible to datetime

and is swallowed up by this `except` statement:

https://github.com/aadel/sqlalchemy-solr/blob/56d46f90fdc522ad9113d8efde592d6a9868bd10/sqlalchemy_solr/solrdbapi/_solrdbapi.py#L108-L109

The code can be made to return something usable more useful by changing this section:

https://github.com/aadel/sqlalchemy-solr/blob/56d46f90fdc522ad9113d8efde592d6a9868bd10/sqlalchemy_solr/solrdbapi/_solrdbapi.py#L103-L107

So that the `except` statement catches `(ValueError, TypeError)` rather than just `ValueError`).

The code then returns the array as a string, e.g. `[value,value]`.  This is better than crashing, but doesn't seem ideal. Is there a good way to handle Solr multivalued fields so the resulting `list()`s are handled as `ARRAY[string]` or whatever makes sense in SQL Alchemy?

**Comment by aadel** [comment]
Hi @anjackson! Thank you for bringing this issue up. I guess the the best approach is introducing a new vendor specific type that handles multivalued fields. I'm linking this issue to the PR and accepting it as an intermediate solution.
