### ISSUE TITLE
For Collections containing dashes "-" , SQL Statements return JSON decoder error

### ISSUE THREAD

**Issue by aehmohamed** [aadel/sqlalchemy-solr#6]
Hi,
I tried using sqlalchemy-solr with Superset version 0.999.0dev with several collections containing dashes "-", the select statements return a JSON Decoder error.
Through wireshark I can Solr replied back with a JSON response but looks like ;
"
{\n
"result-set":{\n
"docs":[{\n
"field1":"value1"}\n
,{\n
"EOF":true,\n
"RESPONSE_TIME":100}]}}
\n
"
The last \n is due to Wireshark display most probably.

I tried the equivalent GET URL in the browser and I could see the expected normal query result ;
http://host:port/solr/collection-1/sql?stmt=SELECT+field1+from+%60collection-1%60+limit+1

%60 is used to escape the dashes "-" in the collection name collection-1

**Comment by aehmohamed** [comment]
Hi, I did multiple tests and confirmed, the parsing error occurs only when the collection name has a special character like dash "-" in my case.
Is there a parsing resolution or an encoding option to fix this ?

**Comment by aadel** [comment]
The issue was due to quoting that Superset does when table names have special characters which is unrecognized by Solr. Using unquoted tables names resolves this issue.

**Comment by aehmohamed** [comment]
Ok I tried the new version but I am not sure if there is a mistake from my side or this is another issue  ;

1. Using unquoted collection names for the collection names with dashes; gives parsing error due to "-".
2. Using quoted collection names ; Generally works fine now, but for some fields that have list values, I get another error due to type conversion probably ; "TypeError: <class 'list'> is not convertible to datetime", if I query fields that have non-list values I get results.

I am attaching the document collection  and my query ;
Indexed into solr through UI ; 
{"document_id": 1, "book":"Alice in Wonder Land"},
{"document_id": 1, "book":"Not Alice in Wonder Land"},
{"document_id": 2, "book":"1984"}

resultsSolr=engineSolr.execute('select _version_ from `col-2` limit 5') --> Gives Results
resultsSolr=engineSolr.execute('select book from `col-2` limit 5') ---> Gives TypeError: <class 'list'> is not convertible to datetime


![image](https://user-images.githubusercontent.com/46297147/119101648-33a57f00-b9e7-11eb-9f20-1a3e8f12f4ff.png)

Facet Query;
http://192.168.1.201:8983/solr/#/col-2/query
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":70,
    "params":{
      "q":"*:*"}},
  "response":{"numFound":3,"start":0,"maxScore":1.0,"numFoundExact":true,"docs":[
      {
        "document_id":[2],
        "book":["1984"],
        "id":"6ebe5c73-04af-4790-ba3b-baf51b3482b8",
        "_version_":1700352897856831488},
      {
        "document_id":[1],
        "book":["Alice in Wonder Land"],
        "id":"9fe7a441-b93d-4869-bbe7-db8ad6f37b4b",
        "_version_":1700352880719953920},
      {
        "document_id":[1],
        "book":["Not Alice in Wonder Land"],
        "id":"112e5900-550e-4921-9c60-13d7bb2d9b40",
        "_version_":1700352889620267008}]
  }}

**Comment by aehmohamed** [comment]
![image](https://user-images.githubusercontent.com/46297147/119102099-a9a9e600-b9e7-11eb-9d6b-1be7507ee393.png)

**Comment by aehmohamed** [comment]
The same query works fine in superset, but I get the TypeError when I run it in python console.

**Comment by aadel** [comment]
It seems that these are two different issues. Actually, quoting happens automatically when collection names have special characters. The second issue, which is a type conversion issue, affects 0.2.2 and is resolved in 0.2.2.1 though.
